# Generated by Django 3.2.8 on 2021-11-09 08:56

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('django_nextflow', '0002_auto_20211106_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='created',
            field=models.IntegerField(default=time.time),
        ),
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='processexecution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
