# Generated by Django 4.0 on 2022-06-16 10:48

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('django_nextflow', '0004_execution_data_params_execution_execution_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='created',
            field=models.FloatField(default=time.time),
        ),
    ]
